--- 
language: cpp
compiler: 
- gcc
env: 
install:
- sudo apt-get install libboost-dev
- sudo apt-get install libboost-thread-dev
- sudo apt-get install libboost-system-dev
before_script:
script: 
- make && ./lightseek_tests -ojunit
